# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Share Economy
tagline:          'A Jekyll theme'
description:      'Share Economy 相关文章翻译、收集'
url:              http://jackzhang1988.github.io/ShareEconomy/
baseurl:          /ShareEconomy/

author:
  name:           'Jianbo Zhang'
  url:            

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/JackZhang1988/ShareEconomy
